# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'JKYDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JKYDemo

  #pod ‘JKYKit’, :path => ‘../JKYKit/’

  pod 'Masonry',        '~> 1.0.2'
  pod 'pop',            '~> 1.0'

  target 'JKYDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JKYDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
